version: '2'
services:
  web:
    build: .
    ports:
      - "5000:5000"
    links:
      - db:mongodb
    container_name: todo_app
    depends_on:
      - db
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    container_name: todo_db